### ISSUE TITLE
Generic Method = > projection Bug

### ISSUE THREAD

**Issue by faker-ben-ali** [Cosium/spring-data-jpa-entity-graph#152]
When we try to work with projection and java generic ,an error is triggered 
Generic Repository Method Exemple
public <T> T findUserByUsernameOrEmail(String username,EntityGraph graph,Class<T> type)
an error triggerd
java.lang.NullPointerException: null
	at java.base/java.lang.Class.isAssignableFrom(Native Method) ~[na:na]
	at com.cosium.spring.data.jpa.entity.graph.core@3.2.1/com.cosium.spring.data.jpa.entity.graph.repository.support.EntityGraphQueryHintCandidates.canApplyEntityGraph(EntityGraphQueryHintCandidates.java:139) ~[spring-data-jpa-entity-graph-3.2.1.jar:na]........

**Comment by reda-alaoui** [comment]
Bug template bypassed => issue closed.
