### ISSUE TITLE
Couldn't start the application after upgrading both Spring Boot and this library to 2.3.0

### ISSUE THREAD

**Issue by jamestrandung** [Cosium/spring-data-jpa-entity-graph#41]
I have the following generic repo in my application.

````
@NoRepositoryBean
public interface BaseDeploymentRepo<T extends Deployment> extends EntityGraphJpaRepository<T, Long> {
    @Query(value="SELECT D"
           + "    FROM #{#entityName} D"
           + "    WHERE D.workspaceCode = :workspaceCode"
           + "    AND D.startDate <= :rangeEndDate"
           + "    AND D.endDate >= :rangeStartDate")
    // The [rangeStartDate, rangeEndDate] must have an overlap with [startDate, endDate] => startDate <= rangeEndDate && endDate >= rangeStartDate
    List<T> findAllDeploymentsWithinRange(String workspaceCode, LocalDate rangeStartDate, LocalDate rangeEndDate, EntityGraph entityGraph);
}
````

When I start the application after upgrading to 2.3.0, I'm seeing the following error in log.

````
Caused by: java.lang.IllegalStateException: Using named parameters for method public abstract java.util.List com.ft.common.db.customer.repo.BaseDeploymentRepo.findAllDeploymentsWithinRange(java.lang.String,java.time.LocalDate,java.time.LocalDate,com.cosium.spring.data.jpa.entity.graph.domain.EntityGraph) but parameter 'Optional[entityGraph]' not found in annotated query 'SELECT D    FROM #{#entityName} D    WHERE D.workspaceCode = :workspaceCode    AND D.startDate <= :rangeEndDate    AND D.endDate >= :rangeStartDate'!
	at org.springframework.data.jpa.repository.query.JpaQueryMethod.assertParameterNamesInAnnotatedQuery(JpaQueryMethod.java:157)
	at org.springframework.data.jpa.repository.query.JpaQueryMethod.<init>(JpaQueryMethod.java:136)
	at com.cosium.spring.data.jpa.entity.graph.repository.query.EntityGraphAwareJpaQueryMethod.<init>(EntityGraphAwareJpaQueryMethod.java:18)
	at com.cosium.spring.data.jpa.entity.graph.repository.query.EntityGraphAwareJpaQueryMethodFactory.build(EntityGraphAwareJpaQueryMethodFactory.java:22)
	at org.springframework.data.jpa.repository.query.JpaQueryLookupStrategy$AbstractQueryLookupStrategy.resolveQuery(JpaQueryLookupStrategy.java:81)
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.lookupQuery(QueryExecutorMethodInterceptor.java:99)
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.lambda$mapMethodsToQuery$1(QueryExecutorMethodInterceptor.java:92)
````

This didn't happen when I was on Spring Boot 2.2.7 and library 2.2.8.

**Comment by reda-alaoui** [comment]
You are using the combination of spring-data-jpa version and spring-data-jpa-entity-graph version.

**Comment by reda-alaoui** [comment]
Or you are missing the repository bean factory. I recommend you to read the documentation again.

**Comment by jamestrandung** [comment]
@reda-alaoui 

I've used this library for a year and a half. I didn't have any issues with previous versions. I only see this exception after upgrading to 2.3.0 as mentioned.

Below is the `repositoryFactoryBeanClass` setup.

````
@Configuration
@ConditionalOnClass(EntityManagerFactory.class)
@EnableJpaRepositories(
        repositoryFactoryBeanClass=EntityGraphJpaRepositoryFactoryBean.class,
        entityManagerFactoryRef=DatabaseConfiguration.ENTITY_FACTORY_MANAGER_CUSTOMER,
        transactionManagerRef=DatabaseConfiguration.TRANSACTION_MANAGER_CUSTOMER,
        basePackages={ "com.ft.demo.db.customer.repo" },
        considerNestedRepositories=true)
public class DemoCustomerDatabaseConfiguration {
    @Bean
    public CustomerPackagesForEntities demoCustomerPackagesForEntities() {
        return new CustomerPackagesForEntities(new String[] { "com.ft.demo.db.customer.domain" });
    }
}
````

From `pom.xml` of Spring Boot, the version of Spring Data JPA is the same as Spring Boot version.


      <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-data-jpa</artifactId>
        <version>${spring-boot.version}</version>
      </dependency>

And from your documentation, 2.3.0 should go with 2.3.0. So what am I missing here?

![image](https://user-images.githubusercontent.com/3972929/82750182-f5c84780-9de0-11ea-8b6d-9682bcb173fd.png)

**Comment by reda-alaoui** [comment]
I am sorry, I misread the exception. Also since you provided spring boot version and I don’t know to which spring data jpa version they relate, I assumed there was a misconfiguration.

Looks like there is a bug here.

**Comment by devnied** [comment]
I have the same issue with Spring data 2.3.0 and spring-data-jpa-entity-graph 2.3.0 dependencies and the usage of custom query with @Query.

```java
Caused by: java.lang.IllegalStateException: Using named parameters for method public abstract org.springframework.data.domain.Page com.xxx.repository.DeployPlanDetailRepository.findAllByDeployPlan_Id(java.lang.Long,org.springframework.data.domain.Pageable,com.cosium.spring.data.jpa.entity.graph.domain.EntityGraph) but parameter 'Optional[entityGraph]' not found in annotated query 'SELECT d FROM DeployPlanDetail d JOIN d.deployPlan deployPlan where deployPlan.id = :id'!
 	at org.springframework.data.jpa.repository.query.JpaQueryMethod.assertParameterNamesInAnnotatedQuery(JpaQueryMethod.java:157)
 	at org.springframework.data.jpa.repository.query.JpaQueryMethod.<init>(JpaQueryMethod.java:136)
 	at com.cosium.spring.data.jpa.entity.graph.repository.query.EntityGraphAwareJpaQueryMethod.<init>(EntityGraphAwareJpaQueryMethod.java:18)
 	at com.cosium.spring.data.jpa.entity.graph.repository.query.EntityGraphAwareJpaQueryMethodFactory.build(EntityGraphAwareJpaQueryMethodFactory.java:22)
 	at org.springframework.data.jpa.repository.query.JpaQueryLookupStrategy$AbstractQueryLookupStrategy.resolveQuery(JpaQueryLookupStrategy.java:81)
 	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.lookupQuery(QueryExecutorMethodInterceptor.java:99)
 	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.lambda$mapMethodsToQuery$1(QueryExecutorMethodInterceptor.java:92)
```
